### ISSUE TITLE
Project solution copied from one system to another shows an error

### ISSUE THREAD

**Issue by Thickar** [sgbj/generator-aspnetcore-angular2#13]
This is the error that shows while running the project generated in one machine in another.
![capture](https://cloud.githubusercontent.com/assets/21097469/17896561/b409a69a-696e-11e6-97c6-0ad138883428.PNG)

What could be the issue and how to solve it ?

**Comment by sgbj** [comment]
[This question on StackOverflow](http://stackoverflow.com/questions/33276878/iis-express-500-19-cannot-read-configuration-file-because-its-looking-at-th) looks very close to the error you're seeing.

Can you try closing Visual Studio, deleting the `.vs` hidden folder in the solution directory, and reopening Visual Studio to see if that fixes it?

You might also try any of the other answers that have been posted on that question.

**Comment by Thickar** [comment]
Issue is resolved, deleting .vs worked.Thank you :+1:
